---

- name: Configure iptables
  include_tasks: iptables.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "6"

- name: Configure firewalld
  include_tasks: firewalld.yml
  when:
    - ansible_distribution == "CentOS"
    - ansible_distribution_major_version == "7"
